export const PLANT_PRICES: Record<string, number> = {
  bean:            2,
  tomato:          2,
  broccoli:        2,
  chili:           2,
  bulbino:         15,
  glowberry:       20,
  ivy:             7,
  jacaranda_tree:  18,
  lettuce:         4,
  neon_mould:      25,
  poison_cabbage:  12,
  raspberry:       9,
  rhubarb:         7,
  strawberry:      11,
  watermelon:      8,
};
