export type Recipe = {
  filename: string;
  name: string;
  price: number;
};

// Keys: two game species sorted alphabetically, joined with '+'.
// e.g. bean + tomato → 'bean+tomato', chili + broccoli → 'broccoli+chili'
// To add a recipe: find the alphabetically-first species, join with '+', set name and price.
export const RECIPES: Record<string, Recipe> = {
  'bean+bean':                  { filename: 'bean_bean.png',                  name: 'Refried Beans',                            price: 6   },
  'bean+broccoli':              { filename: 'bean_broccoli.png',              name: 'Vegetable Stir Fry',                       price: 6   },
  'bean+bulbino':               { filename: 'bean_bulbino.png',               name: 'Farmer Bulbino',                           price: 70  },
  'bean+chili':                 { filename: 'chili_bean.png',                 name: 'Spicy Bean Jar',                           price: 6   },
  'bean+glowberry':             { filename: 'glowberry_beans.png',            name: 'Glowing Bean Salad',                       price: 70  },
  'bean+ivy':                   { filename: 'beans_ivy.png',                  name: 'Decorative Pickled Beans',                 price: 20  },
  'bean+jacaranda_tree':        { filename: 'bean_jacaranda.png',             name: 'Purple Pickled Beans',                     price: 20  },
  'bean+neon_mould':            { filename: 'bean_neon_mould.png',            name: 'Indestructible Beans',                     price: 70  },
  'bean+poison_cabbage':        { filename: 'bean_poison_cabbage.png',        name: 'Deadly Bean Soup',                         price: 70  },
  'bean+raspberry':             { filename: 'bean_raspberry.png',             name: 'Experimental Vegetable Medley',            price: 10  },
  'bean+rhubarb':               { filename: 'bean_rhubarb.png',               name: 'Pickled Beans with Rhubarb Chunks',        price: 6   },
  'bean+strawberry':            { filename: 'bean_strawberry.png',            name: 'Strawberry Flavoured Can of Beans',        price: 10  },
  'bean+tomato':                { filename: 'bean-tomato.png',                name: 'Spring Vegetable Medley',                  price: 6   },
  'bean+watermelon':            { filename: 'bean_watermelon.png',            name: 'Summer Beans',                             price: 10  },

  'broccoli+broccoli':          { filename: 'broccoli_broccoli.png',          name: 'Broccolini',                               price: 6   },
  'broccoli+bulbino':           { filename: 'broccoli_bulbino.png',           name: 'Broccoli-haired Bulbino',                  price: 70  },
  'broccoli+chili':             { filename: 'broccoli_chili.png',             name: 'Spicy Charred Broccoli',                   price: 6   },
  'broccoli+glowberry':         { filename: 'broccoli_glowberry.png',         name: 'Spellbound stir-fry',                      price: 70  },
  'broccoli+ivy':               { filename: 'broccoli_ivy.png',               name: 'Broccoli Crown',                           price: 20  },
  'broccoli+jacaranda_tree':    { filename: 'jacaranda_broccoli.png',         name: 'Texas-sized Purple Broccoli',              price: 20  },
  'broccoli+lettuce':           { filename: 'lettuce_broccoli.png',           name: 'Green Crunch Salad',                       price: 6   },
  'broccoli+neon_mould':        { filename: 'broccoli_neon_mould.png',        name: 'Green Mould Soup',                         price: 70  },
  'broccoli+poison_cabbage':    { filename: 'broccoli_poison_cabbage.png',    name: 'Scary Roasted Broccoli',                   price: 70  },
  'broccoli+raspberry':         { filename: 'broccoli_raspberry.png',         name: 'Tangy Vegetable Medley',                   price: 10  },
  'broccoli+rhubarb':           { filename: 'broccoli_rhubarb.png',           name: 'Broccoli Salad with Rhubarb Dressing',     price: 6   },
  'broccoli+strawberry':        { filename: 'broccoli_strawberries.png',      name: 'Fruit and Vegetable Slaw',                 price: 10  },
  'broccoli+tomato':            { filename: 'broccoli_tomato.png',            name: 'Macaroni Salad with Veggies',              price: 6   },
  'broccoli+watermelon':        { filename: 'broccoli_watermelon.png',        name: 'Green Gazpacho',                           price: 10  },

  'bulbino+bulbino':            { filename: 'bulbino-bulbino.png',            name: 'Royal Bulbino',                            price: 100 },
  'bulbino+chili':              { filename: 'chili_bulbino.png',              name: 'Flame Bulbino',                            price: 70  },
  'bulbino+glowberry':          { filename: 'glowberry_bulbino.png',          name: 'Blue Bulbino',                             price: 100 },
  'bulbino+ivy':                { filename: 'bulbino_ivy.png',                name: 'Fancy Bulbino',                            price: 100 },
  'bulbino+jacaranda_tree':     { filename: 'bulbino_jacaranda.png',          name: 'Purple Bulbino',                           price: 100 },
  'bulbino+lettuce':            { filename: 'bulbino_lettuce.png',            name: 'Bunny Bulbino',                            price: 100 },
  'bulbino+neon_mould':         { filename: 'bulbino_neon_mould.png',         name: 'Neon Bulbino',                             price: 100 },
  'bulbino+poison_cabbage':     { filename: 'bulbino_poison_cabbage.png',     name: 'Sinister Bulbino',                         price: 100 },
  'bulbino+rhubarb':            { filename: 'bulbino_rhubarb.png',            name: 'Rustic Bulbino',                           price: 100 },
  'bulbino+strawberry':         { filename: 'bulbino_strawberry.png',         name: 'Sweet Bulbino',                            price: 80  },
  'bulbino+tomato':             { filename: 'bulbino_tomato.png',             name: 'Bulbino with Spaghetti',                   price: 70  },
  'bulbino+watermelon':         { filename: 'bulbino_watermelon.png',         name: 'Summer Bulbino',                           price: 80  },

  'chili+chili':                { filename: 'chili-chili.png',                name: 'Chili Flakes',                             price: 6   },
  'chili+glowberry':            { filename: 'chili_glowberry.png',            name: 'Blue Chili Jam',                           price: 70  },
  'chili+ivy':                  { filename: 'chili_ivy.png',                  name: 'Decorative Pickled Peppers',               price: 20  },
  'chili+jacaranda_tree':       { filename: 'chili_jacaranda.png',            name: 'Purple Pickled Peppers',                   price: 20  },
  'chili+lettuce':              { filename: 'chili_lettuce.png',              name: 'Spicy Lettuce Bowl',                       price: 6   },
  'chili+neon_mould':           { filename: 'chili_neon_mould.png',           name: 'Radioactive Salsa',                        price: 70  },
  'chili+poison_cabbage':       { filename: 'chili_poison_cabbage.png',       name: 'Hot Mystery Cabbage Soup',                 price: 70  },
  'chili+raspberry':            { filename: 'chili_raspberry.png',            name: 'Fruit Salsa',                              price: 10  },
  'chili+rhubarb':              { filename: 'chili_rhubarb.png',              name: 'Spicy Rhubarb Margarita',                  price: 6   },
  'chili+strawberry':           { filename: 'chili_strawberry.png',           name: 'Spicy Strawberry Preserve',                price: 10  },
  'chili+tomato':               { filename: 'tomato_chili.png',               name: 'Hot Salsa',                                price: 6   },
  'chili+watermelon':           { filename: 'chili_watermelon.png',           name: 'Spicy Watermelon Lemonade',                price: 10  },

  'glowberry+glowberry':        { filename: 'glowberry-glowberry.png',        name: 'Glowsticks',                               price: 100 },
  'glowberry+ivy':              { filename: 'glowerry_ivy.png',               name: 'Glowberry Tart with Garnish',              price: 80  },
  'glowberry+jacaranda_tree':   { filename: 'glowberry_jacaranda.png',        name: 'Purple Raspberry Lavender Iced Tea',       price: 80  },
  'glowberry+lettuce':          { filename: 'lettuce_glowberry.png',          name: 'Divine Salad',                             price: 100 },
  'glowberry+neon_mould':       { filename: 'glowberry_neon_mould.png',       name: 'Gossamer Berry',                           price: 80  },
  'glowberry+poison_cabbage':   { filename: 'glowberry_poison_cabbage.png',   name: 'Midnight Coleslaw',                        price: 80  },
  'glowberry+raspberry':        { filename: 'raspberry_glowberry.png',        name: 'Berry Sorbet',                             price: 80  },
  'glowberry+rhubarb':          { filename: 'glowberry_rhubarb.png',          name: 'Florescent Rhubarb Pie',                   price: 100 },
  'glowberry+strawberry':       { filename: 'glowberry_strawberry.png',       name: 'Sparkling Lemonade',                       price: 80  },
  'glowberry+tomato':           { filename: 'tomato_glowberry.png',           name: 'Enchanted Salsa',                          price: 70  },
  'glowberry+watermelon':       { filename: 'watermelon_glowberry.png',       name: 'Tropical Slush',                           price: 80  },

  'ivy+ivy':                    { filename: 'ivy-ivy.png',                    name: 'Leafy Party Hat',                          price: 80  },
  'ivy+jacaranda_tree':         { filename: 'jacaranda_ivy.png',              name: 'Violet Wreath',                            price: 80  },
  'ivy+lettuce':                { filename: 'lettuce_ivy.png',                name: 'Fancy Salad',                              price: 70  },
  'ivy+neon_mould':             { filename: 'neon_mould_ivy.png',             name: 'Glowing garland',                          price: 80  },
  'ivy+poison_cabbage':         { filename: 'ivy_poison_cabbage.png',         name: 'Poison Slaw with Fancy Garnish',           price: 80  },
  'ivy+raspberry':              { filename: 'ivy_raspberry.png',              name: 'Decorative Raspberry Crumble',             price: 30  },
  'ivy+rhubarb':                { filename: 'ivy_rhubarb.png',                name: 'Fancy Rhubarb Punch',                      price: 70  },
  'ivy+strawberry':             { filename: 'ivy_strawberry.png',             name: 'Strawberry Lemonade with Decorative Leaf', price: 30  },
  'ivy+tomato':                 { filename: 'tomato_ivy.png',                 name: 'Decorative Vine Tomatoes',                 price: 20  },
  'ivy+watermelon':             { filename: 'watermelon_ivy.png',             name: 'Watermelon Punch with Decorate Leaf',      price: 30  },

  'jacaranda_tree+jacaranda_tree': { filename: 'jacaranda-jacaranda.png',     name: 'Purple Piñata',                            price: 80  },
  'jacaranda_tree+lettuce':     { filename: 'lettuce_jacaranda.png',          name: 'Purple Salad',                             price: 70  },
  'jacaranda_tree+neon_mould':  { filename: 'jacaranda_neon_mould.png',       name: 'Fairy Dust',                               price: 36  },
  'jacaranda_tree+poison_cabbage': { filename: 'poison_cabbage_jacaranda.png', name: 'Poison Purple Pho',                       price: 80  },
  'jacaranda_tree+raspberry':   { filename: 'raspberry_jacaranda.png',        name: 'Purple Raspberry Soufflé',                 price: 30  },
  'jacaranda_tree+rhubarb':     { filename: 'rhubarb_jacaranda.png',          name: 'Purple Rhubarb Crumble',                   price: 70  },
  'jacaranda_tree+strawberry':  { filename: 'strawberry_jacaranda.png',       name: 'Purple Strawberry Pie',                    price: 30  },
  'jacaranda_tree+tomato':      { filename: 'tomato_jacaranda.png',           name: 'Tomato Soup with Edible Flowers',          price: 20  },
  'jacaranda_tree+watermelon':  { filename: 'jacaranda_watermelon.png',       name: 'Purple Watermelon Lemonade',               price: 30  },

  'lettuce+lettuce':            { filename: 'lettuce_lettuce.png',            name: 'Bowl of Lettuce',                          price: 6   },
  'lettuce+neon_mould':         { filename: 'neon_mould_lettuce.png',         name: 'Radioactive Salad',                        price: 70  },
  'lettuce+poison_cabbage':     { filename: 'poison_cabbage_lettuce.png',     name: 'Noxious Coleslaw',                         price: 70  },
  'lettuce+raspberry':          { filename: 'raspberry_lettuce.png',          name: 'Tangy Fruit Salad',                        price: 10  },
  'lettuce+rhubarb':            { filename: 'lettuce_rhubarb.png',            name: 'Mixed Greens with Rhubarb Vinagrette',     price: 6   },
  'lettuce+strawberry':         { filename: 'strawberry_lettuce.png',         name: 'Pink Salad',                               price: 10  },
  'lettuce+tomato':             { filename: 'tomato_lettuce.png',             name: 'Garden Salad',                             price: 6   },
  'lettuce+watermelon':         { filename: 'lettuce_watermelon.png',         name: 'Glass of Water',                           price: 10  },

  'neon_mould+neon_mould':      { filename: 'neon_mould-neon_mould.png',      name: 'Alien Creature',                           price: 80  },
  'neon_mould+poison_cabbage':  { filename: 'neon_mould_poison_cabbage.png',  name: 'Nuclear Waste',                            price: 80  },
  'neon_mould+raspberry':       { filename: 'neon_mould_raspberry.png',       name: 'Neon Raspberry Lemonade',                  price: 80  },
  'neon_mould+rhubarb':         { filename: 'neon_mould_rhubarb.png',         name: 'Neon Rhubarb Punch',                       price: 100 },
  'neon_mould+strawberry':      { filename: 'neon_mould_strawberry.png',      name: 'Neon Strawberry Sorbet',                   price: 80  },
  'neon_mould+tomato':          { filename: 'tomato_neon_mould.png',          name: 'Strangely Glowing Rotten Tomato',          price: 70  },
  'neon_mould+watermelon':      { filename: 'neon_mould_watermelon.png',      name: 'Neon Granita',                             price: 80  },

  'poison_cabbage+raspberry':   { filename: 'raspberry_poison_cabbage.png',   name: 'Disgusting Tart',                          price: 80  },
  'poison_cabbage+rhubarb':     { filename: 'rhubarb_poison_cabbage.png',     name: 'Poison Red Coleslaw',                      price: 100 },
  'poison_cabbage+strawberry':  { filename: 'strawberry_cabbage.png',         name: 'Strawberry Cabbage Sludge',                price: 80  },
  'poison_cabbage+tomato':      { filename: 'tomato_poison_cabbage.png',      name: 'Sentient Cabbage Rolls',                   price: 70  },
  'poison_cabbage+watermelon':  { filename: 'watermelon_poison_cabbage.png',  name: 'Putrid Watermelon',                        price: 80  },

  'raspberry+raspberry':        { filename: 'raspberry-raspberry.png',        name: 'Raspberry Syrup',                          price: 16  },
  'raspberry+rhubarb':          { filename: 'raspberry_rhubarb.png',          name: 'Raspberry Rhubarb Crumble',                price: 10  },
  'raspberry+strawberry':       { filename: 'raspberry_strawberry.png',       name: 'Berry Bowl',                               price: 16  },
  'raspberry+tomato':           { filename: 'tomato_raspberry.png',           name: 'Tangy Gazpacho',                           price: 10  },
  'raspberry+watermelon':       { filename: 'raspberry_watermelon.png',       name: 'Raspberry Watermelon Splash',              price: 16  },

  'rhubarb+rhubarb':            { filename: 'rhubarb-rhubarb.png',            name: 'Rhubarb Jam',                              price: 6   },
  'rhubarb+strawberry':         { filename: 'strawberry_rhubarb.png',         name: 'Strawberry Rhubarb Pie',                   price: 10  },
  'rhubarb+tomato':             { filename: 'tomato_rhubarb.png',             name: 'Tomato Rhubarb Chutney',                   price: 6   },
  'rhubarb+watermelon':         { filename: 'watermelon_rhubarb.png',         name: 'Rhubarb Watermelon Punch',                 price: 15  },

  'strawberry+strawberry':      { filename: 'strawberry-strawberry.png',      name: 'Strawberry Jam',                           price: 16  },
  'strawberry+tomato':          { filename: 'tomato_strawberry.png',          name: 'Tomato-Strawberry Basalmic Vinagrette',    price: 10  },
  'strawberry+watermelon':      { filename: 'strawberry_watermelon.png',      name: 'Pink Lemonade',                            price: 16  },

  'tomato+tomato':              { filename: 'tomato_tomato.png',              name: 'Passata',                                  price: 6   },
  'tomato+watermelon':          { filename: 'tomato_watermelon.png',          name: 'Tomato Watermelon Gazpacho',               price: 10  },

  'watermelon+watermelon':      { filename: 'watermelon-watermelon.png',      name: 'Agua Fresca',                              price: 16  },
};
