export type Recipe = {
  filename: string;
  name: string;
  price: number;
};

// Keys: two game species sorted alphabetically, joined with '+'.
// e.g. bean + tomato → 'bean+tomato', chili + broccoli → 'broccoli+chili'
// To add a recipe: find the alphabetically-first species, join with '+', set name and price.
export const RECIPES: Record<string, Recipe> = {
  'bean+broccoli':              { filename: 'bean_broccoli.png',              name: 'Bean & Broccoli Stir Fry',         price: 18 },
  'bean+bulbino':               { filename: 'bean_bulbino.png',               name: 'Bulbino Bean Stew',                price: 22 },
  'bean+chili':                 { filename: 'chili_bean.png',                 name: 'Chili Beans',                      price: 16 },
  'bean+glowberry':             { filename: 'glowberry_beans.png',            name: 'Glowing Bean Salad',               price: 28 },
  'bean+ivy':                   { filename: 'beans_ivy.png',                  name: 'Ivy Bean Wrap',                    price: 14 },
  'bean+jacaranda_tree':        { filename: 'bean_jacaranda.png',             name: 'Jacaranda Bean Dish',              price: 26 },
  'bean+neon_mould':            { filename: 'bean_neon_mould.png',            name: 'Neon Bean Mould',                  price: 32 },
  'bean+poison_cabbage':        { filename: 'bean_poison_cabbage.png',        name: 'Daring Bean Slaw',                 price: 20 },
  'bean+raspberry':             { filename: 'bean_raspberry.png',             name: 'Berry Bean Bowl',                  price: 17 },
  'bean+rhubarb':               { filename: 'bean_rhubarb.png',               name: 'Rhubarb Bean Tart',                price: 15 },
  'bean+strawberry':            { filename: 'bean_strawberry.png',            name: 'Strawberry Bean Compote',          price: 19 },
  'bean+tomato':                { filename: 'bean-tomato.png',                name: 'Classic Tomato Beans',             price: 14 },
  'bean+watermelon':            { filename: 'bean_watermelon.png',            name: 'Watermelon Bean Salsa',            price: 16 },

  'broccoli+bulbino':           { filename: 'broccoli_bulbino.png',           name: 'Bulbino Broccoli Bake',            price: 24 },
  'broccoli+chili':             { filename: 'broccoli_chili.png',             name: 'Chili Broccoli Sauté',             price: 18 },
  'broccoli+glowberry':         { filename: 'broccoli_glowberry.png',         name: 'Glowberry Broccoli Salad',         price: 29 },
  'broccoli+ivy':               { filename: 'broccoli_ivy.png',               name: 'Ivy Broccoli Tangle',              price: 15 },
  'broccoli+jacaranda_tree':    { filename: 'jacaranda_broccoli.png',         name: 'Jacaranda Broccoli Float',         price: 27 },
  'broccoli+lettuce':           { filename: 'lettuce_broccoli.png',           name: 'Garden Green Bowl',                price: 12 },
  'broccoli+neon_mould':        { filename: 'broccoli_neon_mould.png',        name: 'Neon Broccoli Spores',             price: 34 },
  'broccoli+poison_cabbage':    { filename: 'broccoli_poison_cabbage.png',    name: 'Hazard Greens',                    price: 21 },
  'broccoli+raspberry':         { filename: 'broccoli_raspberry.png',         name: 'Raspberry Broccoli Crumble',       price: 18 },
  'broccoli+rhubarb':           { filename: 'broccoli_rhubarb.png',           name: 'Rhubarb Broccoli Bake',            price: 16 },
  'broccoli+strawberry':        { filename: 'broccoli_strawberries.png',      name: 'Strawberry Broccoli Drizzle',      price: 20 },
  'broccoli+tomato':            { filename: 'broccoli_tomato.png',            name: 'Tomato Broccoli Pasta',            price: 17 },
  'broccoli+watermelon':        { filename: 'broccoli_watermelon.png',        name: 'Watermelon Broccoli Splash',       price: 17 },

  'bulbino+chili':              { filename: 'chili_bulbino.png',              name: 'Spicy Bulbino Curry',              price: 28 },
  'bulbino+glowberry':          { filename: 'glowberry_bulbino.png',          name: 'Glowing Bulbino Brew',             price: 38 },
  'bulbino+ivy':                { filename: 'bulbino_ivy.png',                name: 'Bulbino Ivy Wrap',                 price: 24 },
  'bulbino+jacaranda_tree':     { filename: 'bulbino_jacaranda.png',          name: 'Jacaranda Bulbino Stew',           price: 36 },
  'bulbino+lettuce':            { filename: 'bulbino_lettuce.png',            name: 'Bulbino Lettuce Cup',              price: 21 },
  'bulbino+neon_mould':         { filename: 'bulbino_neon_mould.png',         name: 'Neon Bulbino Fungus',              price: 42 },
  'bulbino+poison_cabbage':     { filename: 'bulbino_poison_cabbage.png',     name: 'Dangerous Bulbino Slaw',           price: 30 },
  'bulbino+rhubarb':            { filename: 'bulbino_rhubarb.png',            name: 'Bulbino Rhubarb Crumble',          price: 25 },
  'bulbino+strawberry':         { filename: 'bulbino_strawberry.png',         name: 'Bulbino Strawberry Jam',           price: 29 },
  'bulbino+tomato':             { filename: 'bulbino_tomato.png',             name: 'Bulbino Tomato Soup',              price: 26 },
  'bulbino+watermelon':         { filename: 'bulbino_watermelon.png',         name: 'Bulbino Watermelon Punch',         price: 26 },

  'chili+glowberry':            { filename: 'chili_glowberry.png',            name: 'Fire & Glow Salsa',               price: 33 },
  'chili+ivy':                  { filename: 'chili_ivy.png',                  name: 'Ivy Chili Tangle',                 price: 19 },
  'chili+jacaranda_tree':       { filename: 'chili_jacaranda.png',            name: 'Jacaranda Chili Sauce',            price: 31 },
  'chili+lettuce':              { filename: 'chili_lettuce.png',              name: 'Chili Lettuce Crunch',             price: 16 },
  'chili+neon_mould':           { filename: 'chili_neon_mould.png',           name: 'Radioactive Chili',               price: 38 },
  'chili+poison_cabbage':       { filename: 'chili_poison_cabbage.png',       name: 'Double Danger Slaw',              price: 25 },
  'chili+raspberry':            { filename: 'chili_raspberry.png',            name: 'Chili Raspberry Jam',             price: 23 },
  'chili+rhubarb':              { filename: 'chili_rhubarb.png',              name: 'Chili Rhubarb Compote',           price: 20 },
  'chili+strawberry':           { filename: 'chili_strawberry.png',           name: 'Chili Strawberry Salsa',          price: 24 },
  'chili+tomato':               { filename: 'tomato_chili.png',               name: 'Spicy Tomato Sauce',              price: 21 },
  'chili+watermelon':           { filename: 'chili_watermelon.png',           name: 'Chili Watermelon Rind',           price: 21 },

  'glowberry+ivy':              { filename: 'glowerry_ivy.png',               name: 'Glowing Ivy Brew',                price: 30 },
  'glowberry+jacaranda_tree':   { filename: 'glowberry_jacaranda.png',        name: 'Luminous Jacaranda Tonic',        price: 41 },
  'glowberry+lettuce':          { filename: 'lettuce_glowberry.png',          name: 'Glowing Garden Salad',            price: 27 },
  'glowberry+neon_mould':       { filename: 'glowberry_neon_mould.png',       name: 'Radioactive Glow Mould',          price: 48 },
  'glowberry+poison_cabbage':   { filename: 'glowberry_poison_cabbage.png',   name: 'Toxic Glow Slaw',                 price: 35 },
  'glowberry+raspberry':        { filename: 'raspberry_glowberry.png',        name: 'Glow Raspberry Juice',            price: 32 },
  'glowberry+rhubarb':          { filename: 'glowberry_rhubarb.png',          name: 'Glowing Rhubarb Crumble',         price: 30 },
  'glowberry+strawberry':       { filename: 'glowberry_strawberry.png',       name: 'Glowing Strawberry Jam',          price: 34 },
  'glowberry+tomato':           { filename: 'tomato_glowberry.png',           name: 'Glowing Tomato Sauce',            price: 31 },
  'glowberry+watermelon':       { filename: 'watermelon_glowberry.png',       name: 'Glowing Watermelon Punch',        price: 31 },

  'ivy+jacaranda_tree':         { filename: 'jacaranda_ivy.png',              name: 'Jacaranda Ivy Tea',               price: 27 },
  'ivy+lettuce':                { filename: 'lettuce_ivy.png',                name: 'Ivy Lettuce Wrap',                price: 13 },
  'ivy+neon_mould':             { filename: 'neon_mould_ivy.png',             name: 'Neon Ivy Spores',                 price: 34 },
  'ivy+poison_cabbage':         { filename: 'ivy_poison_cabbage.png',         name: 'Toxic Ivy Slaw',                  price: 21 },
  'ivy+raspberry':              { filename: 'ivy_raspberry.png',              name: 'Ivy Raspberry Tart',              price: 19 },
  'ivy+rhubarb':                { filename: 'ivy_rhubarb.png',                name: 'Ivy Rhubarb Stalk',               price: 16 },
  'ivy+strawberry':             { filename: 'ivy_strawberry.png',             name: 'Ivy Strawberry Preserve',         price: 20 },
  'ivy+tomato':                 { filename: 'tomato_ivy.png',                 name: 'Ivy Tomato Broth',                price: 17 },
  'ivy+watermelon':             { filename: 'watermelon_ivy.png',             name: 'Ivy Watermelon Slush',            price: 17 },

  'jacaranda_tree+lettuce':     { filename: 'lettuce_jacaranda.png',          name: 'Jacaranda Lettuce Roll',          price: 25 },
  'jacaranda_tree+neon_mould':  { filename: 'jacaranda_neon_mould.png',       name: 'Radioactive Jacaranda Pudding',   price: 46 },
  'jacaranda_tree+poison_cabbage': { filename: 'poison_cabbage_jacaranda.png', name: 'Jacaranda Poison Rolls',         price: 33 },
  'jacaranda_tree+raspberry':   { filename: 'raspberry_jacaranda.png',        name: 'Jacaranda Raspberry Fizz',        price: 30 },
  'jacaranda_tree+rhubarb':     { filename: 'rhubarb_jacaranda.png',          name: 'Jacaranda Rhubarb Tart',          price: 28 },
  'jacaranda_tree+strawberry':  { filename: 'strawberry_jacaranda.png',       name: 'Jacaranda Strawberry Delight',    price: 32 },
  'jacaranda_tree+tomato':      { filename: 'tomato_jacaranda.png',           name: 'Jacaranda Tomato Stew',           price: 29 },
  'jacaranda_tree+watermelon':  { filename: 'jacaranda_watermelon.png',       name: 'Jacaranda Watermelon Ice',        price: 29 },

  'lettuce+neon_mould':         { filename: 'neon_mould_lettuce.png',         name: 'Radioactive Lettuce Salad',       price: 32 },
  'lettuce+poison_cabbage':     { filename: 'poison_cabbage_lettuce.png',     name: 'Danger Greens Bowl',              price: 19 },
  'lettuce+raspberry':          { filename: 'raspberry_lettuce.png',          name: 'Raspberry Lettuce Salad',         price: 16 },
  'lettuce+rhubarb':            { filename: 'lettuce_rhubarb.png',            name: 'Rhubarb Lettuce Wrap',            price: 13 },
  'lettuce+strawberry':         { filename: 'strawberry_lettuce.png',         name: 'Strawberry Lettuce Salad',        price: 17 },
  'lettuce+tomato':             { filename: 'tomato_lettuce.png',             name: 'Classic Tomato Salad',            price: 14 },
  'lettuce+watermelon':         { filename: 'lettuce_watermelon.png',         name: 'Watermelon Lettuce Wrap',         price: 14 },

  'neon_mould+poison_cabbage':  { filename: 'neon_mould_poison_cabbage.png',  name: 'Doubly Toxic Mould',              price: 40 },
  'neon_mould+raspberry':       { filename: 'neon_mould_raspberry.png',       name: 'Radioactive Raspberry Jam',       price: 37 },
  'neon_mould+rhubarb':         { filename: 'neon_mould_rhubarb.png',         name: 'Neon Rhubarb Surprise',           price: 35 },
  'neon_mould+strawberry':      { filename: 'neon_mould_strawberry.png',      name: 'Glowing Strawberry Mould',        price: 39 },
  'neon_mould+tomato':          { filename: 'tomato_neon_mould.png',          name: 'Neon Tomato Sauce',               price: 36 },
  'neon_mould+watermelon':      { filename: 'neon_mould_watermelon.png',      name: 'Radioactive Watermelon Rind',     price: 36 },

  'poison_cabbage+raspberry':   { filename: 'raspberry_poison_cabbage.png',   name: 'Poisoned Raspberry Jam',          price: 24 },
  'poison_cabbage+rhubarb':     { filename: 'rhubarb_poison_cabbage.png',     name: 'Toxic Rhubarb Compote',           price: 22 },
  'poison_cabbage+strawberry':  { filename: 'strawberry_cabbage.png',         name: 'Daring Strawberry Slaw',          price: 26 },
  'poison_cabbage+tomato':      { filename: 'tomato_poison_cabbage.png',      name: 'Toxic Tomato Soup',               price: 23 },
  'poison_cabbage+watermelon':  { filename: 'watermelon_poison_cabbage.png',  name: 'Toxic Watermelon Slush',          price: 23 },

  'raspberry+rhubarb':          { filename: 'raspberry_rhubarb.png',          name: 'Raspberry Rhubarb Crumble',       price: 20 },
  'raspberry+strawberry':       { filename: 'raspberry_strawberry.png',       name: 'Berry Mix Jam',                   price: 23 },
  'raspberry+tomato':           { filename: 'tomato_raspberry.png',           name: 'Tomato Raspberry Sauce',          price: 20 },
  'raspberry+watermelon':       { filename: 'raspberry_watermelon.png',       name: 'Raspberry Watermelon Slush',      price: 20 },

  'rhubarb+strawberry':         { filename: 'strawberry_rhubarb.png',         name: 'Strawberry Rhubarb Tart',         price: 21 },
  'rhubarb+tomato':             { filename: 'tomato_rhubarb.png',             name: 'Tomato Rhubarb Chutney',          price: 18 },
  'rhubarb+watermelon':         { filename: 'watermelon_rhubarb.png',         name: 'Rhubarb Watermelon Cooler',       price: 17 },

  'strawberry+tomato':          { filename: 'tomato_strawberry.png',          name: 'Strawberry Tomato Bruschetta',    price: 22 },
  'strawberry+watermelon':      { filename: 'strawberry_watermelon.png',      name: 'Strawberry Watermelon Punch',     price: 22 },

  'tomato+watermelon':          { filename: 'tomato_watermelon.png',          name: 'Watermelon Tomato Gazpacho',      price: 19 },
};
